# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zk_host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'zk_host',
            },
        ),
        migrations.CreateModel(
            name='Zk_node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=5000)),
                ('zk_id', models.CharField(max_length=2)),
                ('is_sync', models.IntegerField()),
                ('deleted', models.IntegerField()),
                ('sync_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'zk_mode',
            },
        ),
    ]
