# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zk_node',
            name='zk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zk.Zk_host'),
        ),
        migrations.AlterModelTable(
            name='zk_node',
            table='zk_node',
        ),
    ]
